import React, { useState } from 'react';
import { extractFriendlyData } from '../utils/metadataExtractor';
import type { ParsedMetadata } from '../utils/pngParser';
import { Copy, CheckCircle2, Sparkles, AlertCircle, Settings, Cpu } from 'lucide-react';

interface FriendlyDisplayProps {
  metadata: ParsedMetadata;
}

export const FriendlyDisplay: React.FC<FriendlyDisplayProps> = ({ metadata }) => {
  const friendlyData = extractFriendlyData(metadata);

  if (!friendlyData.isRecognized) {
    return null; // Return null if we can't extract friendly data, fallback to raw JSON
  }

  return (
    <div className="friendly-display">
      {friendlyData.generator && (
        <div className="generator-badge">
          <Sparkles size={14} /> Generated by {friendlyData.generator}
        </div>
      )}

      {friendlyData.positivePrompt && (
        <PromptWidget title="Positive Prompt" prompt={friendlyData.positivePrompt} type="positive" />
      )}

      {friendlyData.negativePrompt && (
        <PromptWidget title="Negative Prompt" prompt={friendlyData.negativePrompt} type="negative" />
      )}

      {(friendlyData.generationParams || friendlyData.modelName) && (
        <div className="params-widget">
          <div className="widget-header">
            <Settings size={18} />
            <h4>Generation Parameters</h4>
          </div>
          <div className="params-grid">
            {friendlyData.modelName && (
              <div className="param-item model-param">
                <span className="param-label"><Cpu size={14} /> Model</span>
                <span className="param-value">{friendlyData.modelName}</span>
              </div>
            )}
            {friendlyData.generationParams && Object.entries(friendlyData.generationParams).map(([key, value]) => (
              <div key={key} className="param-item">
                <span className="param-label">{key}</span>
                <span className="param-value">{value}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

const PromptWidget: React.FC<{ title: string; prompt: string; type: 'positive' | 'negative' }> = ({ title, prompt, type }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(prompt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={`prompt-widget ${type}`}>
      <div className="widget-header">
        <div className="widget-title">
          {type === 'positive' ? <Sparkles size={18} /> : <AlertCircle size={18} />}
          <h4>{title}</h4>
        </div>
        <button className="widget-copy" onClick={handleCopy}>
          {copied ? <CheckCircle2 size={14} className="text-green" /> : <Copy size={14} />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
      <div className="widget-content">
        <p>{prompt}</p>
      </div>
    </div>
  );
};
